name: Deploy Preview
on:
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: read
  pull-requests: write

jobs:
  preview:
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      # Pull env vars & project settings for the "preview" environment
      - name: Vercel pull (preview)
        run: npx vercel pull --yes --environment=preview --token "$VERCEL_TOKEN"

      # Build once on the runner to keep deploys reproducible
      - name: Vercel build
        run: npx vercel build --token "$VERCEL_TOKEN"

      # Deploy the prebuilt output as a Preview
      - name: Vercel deploy (preview)
        id: deploy
        run: |
          url=$(npx vercel deploy --prebuilt --token "$VERCEL_TOKEN")
          echo "url=$url" >> $GITHUB_OUTPUT

      # Comment the Preview URL on the PR
      - name: Comment with preview URL
        uses: actions/github-script@v7
        with:
          script: |
            const url = core.getInput('url', { required: true });
            const body = `🚀 Preview ready: ${url}`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body
            });
        env:
          url: ${{ steps.deploy.outputs.url }}
